# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6095a387bdc38ea06970e208dc27f0d59190f482c302b6cbb3953840af8d07a1dd01cb5ba47abad8db3e73a3ab2edee88cf29972d4e8e004e4a252527061690

test:
  secret_key_base: 2cf9d4e21e8a0a664d26b83c540df3275d93c976ccea70f16a857136287c609db8eb2d944c74377e2e66b7b883612c0a471a88bf88f2320719b51bb5a2ea3cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
